spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clinic}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

clinic:
  security:
    secret: YjQzZDc5N2I2OWJkODU2YjNlM2E4ZmVjMTE0M2MzNmYzZTM5NjFjNzQzNjE3M2RjNjJkYTY4NTE5OWFkMWUwMw==
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

  jpa:
    properties:
      hibernate:
        generate_statistics: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG
